### ISSUE TITLE
Question about wrong type of return value(in python) for allocatable real64 arrays(fortran).

### ISSUE THREAD

**Issue by mtsg-DZH** [tchlux/fmodpy#9]
Hi.
when i write fortran file like this
```fortran
subroutine some(array_real64)
    ! use iso_c_binding
    implicit none
    INTEGER :: i
    REAL(kind=8), DIMENSION(:), ALLOCATABLE, INTENT(OUT) :: array_real64
    ALLOCATE (array_real64(4))
    do i = 1, size(array_real64)
        array_real64(i) = 3.14*i
    end do
end subroutine some
```
and python file like this:
```python
import os
dir_name = os.path.dirname(os.path.abspath(__file__))
test_name = os.path.basename(dir_name)
fort_file = os.path.join(dir_name, "real64.f90")
build_dir = os.path.join(dir_name, "fmodpy_real64")
import fmodpy
import numpy as np
RWD = fmodpy.fimport(fort_file, build_dir=build_dir,
                      output_dir=dir_name, rebuild=True)
# input = np.zeros((4),dtype=np.float64,order='F')
out = RWD.some()
print(out)
print(out.dtype)
```
the results is wrong and its type is float32
![image](https://github.com/tchlux/fmodpy/assets/57323621/3aab2932-f525-4b6d-bc1c-74784f0e959c)

If I remove the ALLOCATABLE attribute from the real64 array.
```fortran
REAL(kind=8), DIMENSION(:), INTENT(OUT) :: array_real64
```
and python like this
```python
input = np.zeros((4),dtype=np.float64,order='F')
out = RWD.some(input)
```
The result is correct
![image](https://github.com/tchlux/fmodpy/assets/57323621/1d5d3244-a684-4526-b1ad-ca00408d5b7b)

**Comment by mtsg-DZH** [comment]
The first coding way is not compilable under f2py.
The second method is OK.

**Comment by tchlux** [comment]
Thanks for the detailed write up! Let me investigate and get back to you.

**Comment by tchlux** [comment]
Okay I've found and resolved the issue with a [newly published](https://github.com/tchlux/fmodpy/releases/tag/1.7.1) version [`fmodpy==1.7.1`](https://pypi.org/project/fmodpy/) and [added new test cases](https://github.com/tchlux/fmodpy/commit/98078f07f4305e28e4e9bc15f13706678579f731) to cover this in the future. You should see the correct output now when running your program. Here's what I get now: (image)

<img width="759" alt="image" src="https://github.com/tchlux/fmodpy/assets/7769932/aa7a0fa7-28be-4d55-954c-51008a3d5d3b">

Let me know if you have any other issues, ideas, or feedback.

## Thank you for contributing to `fmodpy`!! ❤️🤓

**Comment by mtsg-DZH** [comment]
Thank !!😍 👍 👍 👍

**Comment by tchlux** [comment]
Also, just so you are aware, the memory that is allocated by Fortran will not be deallocated by python! So it will cause a memory leak if you allow the returned variables to go out of scope and get deleted by python garbage collection.

If you need to handle long running programs, make sure you create a separate fortran subroutine or function for `DEALLOCATE`'ing the array that you allocated previously!
